version: '2' 
services:
  orderer1.fusions360.com:
    image: hyperledger/fabric-orderer
    container_name: orderer1.fusions360.com
    hostname: orderer1.fusions360.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/block/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka1:9092,kafka2:9092,kafka3:9092,kafka4:9092,kafka5:9092]
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer1/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer1/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer0/tls/ca.crt,/var/hyperledger/orderer1/tls/ca.crt, /var/hyperledger/peer0Org1/tls/ca.crt, /var/hyperledger/peer0Org2/tls/ca.crt]
    volumes:
      - ./:/var/hyperledger/orderer/block/
      - ./crypto-config/ordererOrganizations/fusions360.com/orderers/orderer1.fusions360.com/msp/:/var/hyperledger/orderer/msp/
      - ./crypto-config/ordererOrganizations/fusions360.com/orderers/orderer0.fusions360.com/tls/:/var/hyperledger/orderer0/tls/
      - ./crypto-config/ordererOrganizations/fusions360.com/orderers/orderer1.fusions360.com/tls/:/var/hyperledger/orderer1/tls/
      - ./crypto-config/peerOrganizations/org1.fusions361.com/peers/peer0.org1.fusions361.com/tls/:/var/hyperledger/peer0Org1/tls/
      - ./crypto-config/peerOrganizations/org2.fusions362.com/peers/peer0.org2.fusions362.com/tls/:/var/hyperledger/peer0Org2/tls/
    ports:
      - 7050:7050
    extra_hosts:
      - "zookeeper1:52.183.75.10"
      - "zookeeper2:52.175.231.85"
      - "zookeeper3:52.183.28.189"
      - "zookeeper4:52.175.216.219"
      - "zookeeper5:13.66.221.48"
      - "kafka1:52.183.75.10"
      - "kafka2:52.175.231.85"
      - "kafka3:52.183.28.189"
      - "kafka4:52.175.216.219"
      - "kafka5:13.66.221.48"
      - "ca1:52.183.75.10"
      - "ca2:52.175.231.85"
      - "orderer0.fusions360.com:52.183.28.189"
      - "orderer1.fusions360.com:52.175.216.219"
      - "couchdbPeer0Org1:13.66.221.48"
      - "couchdbPeer0Org2:52.183.75.10"
      - "peer0.org1.fusions361.com:52.175.231.85"
      - "peer0.org2.fusions362.com:52.183.28.189"
      - "cliOrg1:52.175.216.219"
      - "cliOrg2:13.66.221.48"