version: '2' 
services:
  peer0.org1.fusions361.com:
    image: hyperledger/fabric-peer
    container_name: peer0.org1.fusions361.com
    hostname: peer0.org1.fusions361.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabriclib_default # must, 'folder name' + '_' + 'networks' ,networks default : 'default'
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=fusions1
      - CORE_PEER_ID=peer0.org1.fusions361.com
      - CORE_PEER_ADDRESS=peer0.org1.fusions361.com:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp/
    volumes:
      - /var/run/:/host/var/run/
      - ./cc02:/opt/gopath/src/cc02/
      - ./:/etc/hyperledger/peer/
      - ./crypto-config/peerOrganizations/org1.fusions361.com/peers/peer0.org1.fusions361.com/msp/:/var/hyperledger/peer/msp/
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    extra_hosts:
      - "zookeeper1:52.183.75.10"
      - "zookeeper2:52.175.231.85"
      - "zookeeper3:52.183.28.189"
      - "zookeeper4:52.175.216.219"
      - "zookeeper5:13.66.221.48"
      - "kafka1:52.183.75.10"
      - "kafka2:52.175.231.85"
      - "kafka3:52.183.28.189"
      - "kafka4:52.175.216.219"
      - "kafka5:13.66.221.48"
      - "ca1:52.183.75.10"
      - "ca2:52.175.231.85"
      - "orderer0.fusions360.com:52.183.28.189"
      - "orderer1.fusions360.com:52.175.216.219"
      - "couchdbPeer0Org1:13.66.221.48"
      - "couchdbPeer0Org2:52.183.75.10"
      - "peer0.org1.fusions361.com:52.175.231.85"
      - "peer0.org2.fusions362.com:52.183.28.189"
      - "cliOrg1:52.175.216.219"
      - "cliOrg2:13.66.221.48"